export const STARTER_RECIPE_CATALOG = [
  {
    slug: 'improvised-medkit',
    name: 'Improvised Medkit',
    description: 'A compact trauma pouch assembled from scavenged field supplies.',
    category: 'consumable',
    difficulty: 'basic',
    ingredients: [
      { resource: 'Bandage Roll', amount: 2 },
      { resource: 'Antiseptic', amount: 1 },
      { resource: 'Scrap Cloth', amount: 1 },
    ],
    bonus_type: 'healing',
    bonus_value: 10,
    output_value: 45,
    output_quantity: 1,
    is_available: true,
  },
  {
    slug: 'scrap-shiv',
    name: 'Scrap Shiv',
    description: 'Crude close-quarters insurance forged from junk metal and wraps.',
    category: 'weapon',
    difficulty: 'basic',
    ingredients: [
      { resource: 'Scrap Metal', amount: 3 },
      { resource: 'Cloth Wrap', amount: 1 },
    ],
    bonus_type: 'none',
    bonus_value: 0,
    output_value: 30,
    output_quantity: 1,
    is_available: true,
  },
  {
    slug: 'field-repair-kit',
    name: 'Field Repair Kit',
    description: 'Portable tools and parts for keeping gear running in bad conditions.',
    category: 'tool',
    difficulty: 'intermediate',
    ingredients: [
      { resource: 'Scrap Metal', amount: 4 },
      { resource: 'Adhesive', amount: 2 },
      { resource: 'Wiring', amount: 2 },
    ],
    bonus_type: 'repair',
    bonus_value: 12,
    output_value: 70,
    output_quantity: 1,
    is_available: true,
  },
  {
    slug: 'reinforced-vest',
    name: 'Reinforced Vest',
    description: 'Layered salvaged plates stitched into a wearable defensive shell.',
    category: 'armor',
    difficulty: 'advanced',
    ingredients: [
      { resource: 'Ballistic Plate', amount: 2 },
      { resource: 'Scrap Metal', amount: 4 },
      { resource: 'Cloth Wrap', amount: 3 },
    ],
    bonus_type: 'defense',
    bonus_value: 18,
    output_value: 140,
    output_quantity: 1,
    is_available: true,
  },
  {
    slug: 'power-cell-upgrade',
    name: 'Power Cell Upgrade',
    description: 'A tuned capacitor package that squeezes more runtime from base systems.',
    category: 'upgrade',
    difficulty: 'advanced',
    ingredients: [
      { resource: 'Battery Cell', amount: 2 },
      { resource: 'Wiring', amount: 3 },
      { resource: 'Circuit Board', amount: 1 },
    ],
    bonus_type: 'power_efficiency',
    bonus_value: 15,
    output_value: 110,
    output_quantity: 1,
    is_available: true,
  },
  {
    slug: 'stabilized-fuel-brick',
    name: 'Stabilized Fuel Brick',
    description: 'Dense barter-grade fuel packs prized by transport crews and outposts.',
    category: 'trade_good',
    difficulty: 'intermediate',
    ingredients: [
      { resource: 'Fuel Sludge', amount: 3 },
      { resource: 'Binding Agent', amount: 1 },
      { resource: 'Canister', amount: 1 },
    ],
    bonus_type: 'none',
    bonus_value: 0,
    output_value: 85,
    output_quantity: 2,
    is_available: true,
  },
  {
    slug: 'longwatch-rifle',
    name: 'Longwatch Rifle',
    description: 'A carefully tuned marksman platform built for quiet overwatch.',
    category: 'weapon',
    difficulty: 'masterwork',
    ingredients: [
      { resource: 'Rifle Receiver', amount: 1 },
      { resource: 'Precision Barrel', amount: 1 },
      { resource: 'Optics Lens', amount: 1 },
      { resource: 'Scrap Metal', amount: 4 },
    ],
    bonus_type: 'accuracy',
    bonus_value: 20,
    output_value: 260,
    output_quantity: 1,
    is_available: true,
  },
] as const;
